server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url:  jdbc:mysql://192.168.56.8:3306/heima?useUnicode=true&amp;characterEncoding=utf8
    username:  root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
      default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl: http://4fwd8p.natappfree.cc/notify/pay

