server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch-cluster
      cluster-nodes: 192.168.56.8:9301
  jackson:
    default-property-inclusion:  non_null
  rabbitmq:
    host: 192.168.56.8
    username: /leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 10   #fetch请求周期为5秒
  instance:
   # lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
   # lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1