server:
  port: 7001
spring:
  application:
    name:  ly-Eureka
eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: false
    fetch-registry: false